/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GroupRouteRouteImport } from './routes/group/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShipmentIndexRouteImport } from './routes/shipment/index'
import { Route as ProductionLineIndexRouteImport } from './routes/production-line/index'
import { Route as GroupChar123GroupIdChar125MembersIndexRouteImport } from './routes/group/{-$groupId}/members/index'
import { Route as GroupChar123GroupIdChar125ContractsIndexRouteImport } from './routes/group/{-$groupId}/contracts/index'

const GroupRouteRoute = GroupRouteRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentIndexRoute = ShipmentIndexRouteImport.update({
  id: '/shipment/',
  path: '/shipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionLineIndexRoute = ProductionLineIndexRouteImport.update({
  id: '/production-line/',
  path: '/production-line/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupChar123GroupIdChar125MembersIndexRoute =
  GroupChar123GroupIdChar125MembersIndexRouteImport.update({
    id: '/{-$groupId}/members/',
    path: '/{-$groupId}/members/',
    getParentRoute: () => GroupRouteRoute,
  } as any)
const GroupChar123GroupIdChar125ContractsIndexRoute =
  GroupChar123GroupIdChar125ContractsIndexRouteImport.update({
    id: '/{-$groupId}/contracts/',
    path: '/{-$groupId}/contracts/',
    getParentRoute: () => GroupRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/group': typeof GroupRouteRouteWithChildren
  '/production-line/': typeof ProductionLineIndexRoute
  '/shipment/': typeof ShipmentIndexRoute
  '/group/{-$groupId}/contracts/': typeof GroupChar123GroupIdChar125ContractsIndexRoute
  '/group/{-$groupId}/members/': typeof GroupChar123GroupIdChar125MembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/group': typeof GroupRouteRouteWithChildren
  '/production-line': typeof ProductionLineIndexRoute
  '/shipment': typeof ShipmentIndexRoute
  '/group/{-$groupId}/contracts': typeof GroupChar123GroupIdChar125ContractsIndexRoute
  '/group/{-$groupId}/members': typeof GroupChar123GroupIdChar125MembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/group': typeof GroupRouteRouteWithChildren
  '/production-line/': typeof ProductionLineIndexRoute
  '/shipment/': typeof ShipmentIndexRoute
  '/group/{-$groupId}/contracts/': typeof GroupChar123GroupIdChar125ContractsIndexRoute
  '/group/{-$groupId}/members/': typeof GroupChar123GroupIdChar125MembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/group'
    | '/production-line/'
    | '/shipment/'
    | '/group/{-$groupId}/contracts/'
    | '/group/{-$groupId}/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/group'
    | '/production-line'
    | '/shipment'
    | '/group/{-$groupId}/contracts'
    | '/group/{-$groupId}/members'
  id:
    | '__root__'
    | '/'
    | '/group'
    | '/production-line/'
    | '/shipment/'
    | '/group/{-$groupId}/contracts/'
    | '/group/{-$groupId}/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupRouteRoute: typeof GroupRouteRouteWithChildren
  ProductionLineIndexRoute: typeof ProductionLineIndexRoute
  ShipmentIndexRoute: typeof ShipmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/group': {
      id: '/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof GroupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipment/': {
      id: '/shipment/'
      path: '/shipment'
      fullPath: '/shipment/'
      preLoaderRoute: typeof ShipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-line/': {
      id: '/production-line/'
      path: '/production-line'
      fullPath: '/production-line/'
      preLoaderRoute: typeof ProductionLineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/{-$groupId}/members/': {
      id: '/group/{-$groupId}/members/'
      path: '/{-$groupId}/members'
      fullPath: '/group/{-$groupId}/members/'
      preLoaderRoute: typeof GroupChar123GroupIdChar125MembersIndexRouteImport
      parentRoute: typeof GroupRouteRoute
    }
    '/group/{-$groupId}/contracts/': {
      id: '/group/{-$groupId}/contracts/'
      path: '/{-$groupId}/contracts'
      fullPath: '/group/{-$groupId}/contracts/'
      preLoaderRoute: typeof GroupChar123GroupIdChar125ContractsIndexRouteImport
      parentRoute: typeof GroupRouteRoute
    }
  }
}

interface GroupRouteRouteChildren {
  GroupChar123GroupIdChar125ContractsIndexRoute: typeof GroupChar123GroupIdChar125ContractsIndexRoute
  GroupChar123GroupIdChar125MembersIndexRoute: typeof GroupChar123GroupIdChar125MembersIndexRoute
}

const GroupRouteRouteChildren: GroupRouteRouteChildren = {
  GroupChar123GroupIdChar125ContractsIndexRoute:
    GroupChar123GroupIdChar125ContractsIndexRoute,
  GroupChar123GroupIdChar125MembersIndexRoute:
    GroupChar123GroupIdChar125MembersIndexRoute,
}

const GroupRouteRouteWithChildren = GroupRouteRoute._addFileChildren(
  GroupRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupRouteRoute: GroupRouteRouteWithChildren,
  ProductionLineIndexRoute: ProductionLineIndexRoute,
  ShipmentIndexRoute: ShipmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
